version: '3'
services:
  db:
    container_name: psql
    restart: always
    image: psql
    build:
      context: ./db
#    volumes: this persists the db code locally
#      - ./db/data/:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DATABASE
  graphql:
    container_name: pgql
    restart: always
    image: graphile/postgraphile
    depends_on:
      - db
    ports:
      - ${GRAPHQL_PORT}
    command: ["postgraphile", "--cors", "--connection", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DATABASE}", "--host", "0.0.0.0", "--port", "${GRAPHQL_PORT}", "--schema", "trials_status_schema"]
    links:
      - db
  scraper:
    container_name: scraper
    # image: dstuck/clinical-trials-api-scraper:latest
    build: ../clinical-trials-api-scraper
    depends_on:
      - graphql
    environment:
      - GRAPHQL_HOST
      - GRAPHQL_PORT
      - SECONDS_BETWEEN_SCRAPES
    restart: always
