version: "3"
services:
  db:
    container_name: psql
    restart: always
    image: psql
    build:
      context: ./db
    #    volumes: this persists the db code locally
    #      - ./db/data/:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DATABASE
    expose:
      - 5432
    ports:
      - "127.0.0.1:5432:5432"
  graphql:
    container_name: pgql
    restart: always
    image: graphile/postgraphile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:1234@db:5432/clinical_trials_status # To be moved to environment file
    expose:
      - 5000
    ports:
      - "${HOST_IP:-127.0.0.1}:${GRAPHQL_PORT}:${GRAPHQL_PORT}"
    command:
      [
        "--cors",
        "--retry-on-init-fail",
        "--connection",
        "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DATABASE}",
        "--host",
        "0.0.0.0",
        "--port",
        "${GRAPHQL_PORT}",
        "--schema",
        "trials_status_schema",
        "${DISABLE_MUTATIONS_FLAG}",
        "--enhance-graphiql",
      ]
    links:
      - db
  scraper:
    container_name: scraper
    # image: dstuck/clinical-trials-api-scraper:latest
    build: ../clinical-trials-api-scraper
    depends_on:
      - graphql
    environment:
      - GRAPHQL_HOST
      - GRAPHQL_PORT
      - SECONDS_BETWEEN_SCRAPES
      - SCRAPER_USE_SQL_FLAG
      - SCRAPER_MAX_ID
    restart: "${RESTART}"
